### ISSUE TITLE
supportted postgresql

### ISSUE THREAD

**Issue by fxf568** [victor-wiki/DatabaseManager#1]
Can postgresql be supported?

**Comment by victor-wiki** [comment]
I'm sorry that the PostgreSQL hasn't been supportted yet and there is no plan to implement that currently. The tool only supports MSSQL, Oracle and MySql, and it utilizes [antlr grammars](https://github.com/antlr/grammars-v4) as the syntax rule, and uses [data type specifications](https://github.com/victor-wiki/DatabaseManager/tree/master/DatabaseInterpreter/DatabaseInterpreter.Core/Config/DataTypeSpecification), [data type mappings](https://github.com/victor-wiki/DatabaseManager/tree/master/DatabaseConverter/DatabaseConverter.Core/Config/DataTypeMapping) for different databases. That is, the most important difference of these databases is the data type and syntax of SQL.

**Comment by victor-wiki** [comment]
The PostgreSql right now has been included into the project, but its script parser is incomplete, you can take a look at the [CodeParser](https://github.com/victor-wiki/CodeParser) which use antlr.
