### ISSUE TITLE
Null Object Reference PLSqlRuleAnalyser

### ISSUE THREAD

**Issue by emrdmrc101** [victor-wiki/DatabaseManager#11]
Hi, I encountered a problem on the PLSQL side, thank you in advance.

**PLSQL Query**

```
WITH
   sum_sales AS
      ( select
      sum(qty) all_sales from sales ),
   number_stores AS
      ( select
      count(*) nbr_stores from stores ),
   sales_by_store AS
      ( select
      stor_name, sum(qty) store_sales from
      stores natural join sales
      group by stor_name)
SELECT
   stores.stor_name
FROM
   stores,
   sum_sales,
   number_stores,
   sales_by_store
where
   store_sales > (all_sales / nbr_stores);
```

**Test Code:** 
```
 PlSqlAnalyser plSqlAnalyser = new PlSqlAnalyser(query);       
var result = plSqlAnalyser.AnalyseCommon();
```

https://github.com/victor-wiki/DatabaseManager/blob/92ed82e633f0ed05753239a86558146328b56548/DatabaseConverter/SqlAnalyser.Core/RuleAnalyser/PlSqlRuleAnalyser.cs#L1342C28-L1342C28

![image](https://github.com/victor-wiki/DatabaseManager/assets/123460401/3cff9b7f-f868-46ef-b7e7-2ed98dc29f9c)

![image](https://github.com/victor-wiki/DatabaseManager/assets/123460401/7a23d69d-4e6b-4561-8224-1c5bb403ee9d)

**Comment by victor-wiki** [comment]
Thanks, the code has been modified. BTW, if you find other issue and figure it out, you can correct the code directly, i'll merge it.
