### ISSUE TITLE
Error: Unknown column C.Generation_Expression when comparing mysql

### ISSUE THREAD

**Issue by oghenez** [victor-wiki/DatabaseManager#9]
I got an error when i tried to compare two mysql database after clicking **Compare** button. See image below.
Is there a fix for this?

![2022-12-26_200816](https://user-images.githubusercontent.com/3947396/209577513-1e99e396-2e04-4fe7-ad21-bd73cc929f4e.jpg)

**Comment by victor-wiki** [comment]
Thanks for your feedback. The issue is due to no detection for mysql version, the column "Generation_Expression" was used since version 5.7.

**Comment by oghenez** [comment]
Any suggestion for a fix?

**Comment by victor-wiki** [comment]
The issue has been fixed yet.
